name: expand
channels:
  - pytorch
dependencies:
  - python==3.8.13
  - cudatoolkit=11.0
  - pytorch==1.7.1
  - torchvision==0.8.2
  - pip=22.3.1
  - pip:
    - click
    - git+https://github.com/openai/CLIP.git
    - ftfy
    - imageio-ffmpeg==0.4.3
    - lpips
    - ninja
    - psutil
    - pyspng
    - scipy
    - tqdm
    - wandb==0.13.9
    - requests
